### ISSUE TITLE
Me again with does not work :-)

### ISSUE THREAD

**Issue by Ofer-Gal** [s-KaiNet/node-pnp-js#1]
[NodePnp.zip](https://github.com/s-KaiNet/node-pnp-js/files/1290951/NodePnp.zip)
I have node –v  v6.10.2
npm –v  3.10.3
tsc –v Version 2.5.2
and npm install all the latest and srill too many errors to display here begining with
> tsc -p tsconfig.json
7960 interface Headers {
             ~~~~~~~
C:/Users/ofer/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts(7960,11): error TS2300: Duplicate identifier 'Headers'.
7969 declare var Headers: {
                 ~~~~~~~
C:/Users/ofer/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts(7969,13): error TS2300: Duplicate identifier 'Headers'.
13093 interface ReadableStream {
                ~~~~~~~~~~~~~~
Same with https://github.com/s-KaiNet/node-pnpjs-sample

**Comment by s-KaiNet** [comment]
Everything in web changes so fast... Sorry, the sample [node-pnpjs-sample](https://github.com/s-KaiNet/node-pnpjs-sample) is also outdated, I've just fixed it to make it work with latest TS and sp-pnp-js.    
You can try to update and run it once again.

**Comment by Ofer-Gal** [comment]
That worked fine.

 

Thank You 

Ofer Gal
