### ISSUE TITLE
Possible to use access_token obtained from azure ad with this?

### ISSUE THREAD

**Issue by nigel-dewar** [s-KaiNet/node-pnp-js#2]
Hi There, this is a question.

I am
Using node.js application using express. NOT using TypeScrupt.
Node App is hosted completely externally. It is NOT an addin.
Node Application authentications through Azure Ad, hence has an access_token available to use.

I did try just using the pnp-js-core library to do this like so

 tried setting the headers on the pnp setup object, like so

```
const pnp = require('sp-pnp-js')

pnp.setup({
                 sp: {
                     baseUrl: "https://mytenant.sharepoint.com",
                    headers: {
                         "Accept": "application/json;odata=verbose",
                         "Authorization": "Bearer " + token
                     }
                }
 }); 

pnp.sp.web.get().then(r => {
    console.log(r);
}); 
```

But got nowhere and just got errors about the headers not being set, even though they are of course.

Will the wrapper you created, allow me to do something like what I am trying to do here?

Many thanks in advance

Nigel Dewar

**Comment by s-KaiNet** [comment]
Hi, 
which oauth flow do you use in order to obtain an access token?

**Comment by nigel-dewar** [comment]
using oauth2 'code' flow. I obtain code in front end first, then pass back to node which goes and gets the token from azure ads endpoint like so

var url = "https://login.microsoftonline.com/common/oauth2/token";

I have tested the access token works good with the O365 graph client, so it access_token should be all good to go.

Cheers for your response

**Comment by s-KaiNet** [comment]
Looks like your issue resolved, so I'm closing this one as well.
